---
aap_download_url: https://developers.redhat.com/content-gateway/file/ansible/Ansible_Automation_Platform_2.4/ansible-automation-platform-setup-bundle-2.4-1-x86_64.tar.gz
aap_download_filename: "{{ aap_download_url | urlsplit('path') | basename}}"
clean_temp_dirs: true