- name: SSH Config File
  when: "'vscode_remotes' in groups"
  template:
    dest: ~/.ssh/config-vscode
    src: ssh_config.j2
  tags: [vscode-ssh-config]

- name: Copy config file
  copy:
    # TODO: merging others
    content: "{{ vs_code_settings | to_json }}"
    dest: "{{ config_dir | default(_settings_dir_by_os[ansible_os_family]) }}/settings.json"
    directory_mode: u=rwx,g=,o=
    mode: preserve
    backup: true