rhel_image_dl_name: "{{ (rhel_image_url | urlsplit('path')).split('/')[-1] }}"
libvirt_images_path: /var/lib/libvirt/images/
rhel_image_dl_path: "{{ libvirt_images_path }}/{{ rhel_image_dl_name }}"
rhel_download_become: true

disk_gb: 80
memory: 4Gb
cpus: 2 # TODO: 4?

cloud_init_content:
  hostname: "{{ vm_name }}"
  fqdn: "{{ fqdn | default(omit) }}"
  password: "{{ user_password }}"
  chpasswd: { expire: false }
  # TODO: ssh keys