- name: Install EPEL if rhel 9
  ansible.builtin.command:
    argv: [dnf, -y, install, https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm]
  # ansible.builtin.package:
  #   name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm"
  become: true
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "9"

- name: Include package vars
  ansible.builtin.import_tasks: packages/include_package_vars.yaml

- name: Remove old packages
  ansible.builtin.package:
    name: "{{ retired_packages }}"
    state: absent
  become: "{{ _is_not_mac }}"
  tags: pkg

- name: Install packages
  ansible.builtin.package:
    name: "{{ packages }}"
  async: "{{ 5 * 60 }}" # 5 mins
  poll: 0
  register: pkg_install
  become: "{{ _is_not_mac }}"
  tags: pkg

# TODO: homebrew_cask is broken in community.general 9.0.1
- name: Install casks
  ansible.builtin.command:
    argv: "{{ base_cmd + args }}"
  async: "{{ 5 * 60 }}" # 5 mins
  poll: 0
  register: cask_install
  tags: [pkg, cask]
  when: _is_mac and (args | length is gt(0))
  vars:
    base_cmd: [brew, install, --cask]
    args: "{{ packages_sys.casks | default([]) }}"

# - name: Install system python packages (mac only for now)
#   ansible.builtin.pip:
#     name: "{{ python_packages | default([]) }}"
#   when: _is_mac
#   become: "{{ ansible_os_family != 'Darwin' }}"
#   tags: pkg