- name: Install EPEL if rhel 9
  ansible.builtin.command:
    argv: [dnf, -y, install, https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm]
  # ansible.builtin.package:
  #   name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm"
  become: true
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "9"

- name: Import common packages
  ansible.builtin.include_vars:
    name: packages_common
    file: packages/common.yaml
  tags: pkg

- name: Import system-specific packages
  ansible.builtin.include_vars:
    name: packages_sys
    file: packages/{{ ansible_system | lower }}.yaml
  tags: [pkg, cask]

# TODO: why was I doing it this way before?
# - name: Import distro/system-specific packages
#   ansible.builtin.include_vars:
#     # this won't cause an error if absent
#     dir: packages
#     files_matching: '{{ ansible_system }}\.yaml'

- name: Combine package specifications
  vars:
    # system is something like linux/darwin
    sys_pkgs: "{{ packages_sys.packages | default([]) }}"
    sys_retired: "{{ packages_sys.retired | default([]) }}"

    # distribution is something like fedora/macos
    dist_pkgs: "{{ packages_sys[(ansible_distribution | lower)] | default([]) }}"
    dist_retired: "{{ packages_sys['retired_' + (ansible_distribution | lower)] | default([]) }}"

    sys_skip: "{{ packages_sys.skip | default([]) }}"

    # TODO: properly handling version checking (IN VARS FILE, NOT HERE)
    # for skipping. Until then, skipping skipping. And also major versioning.

    # sys_skip: "{{ packages_sys['skip_packages_']
    # vars['skip_packages_' + (ansible_system | lower)] | default([]) }}"
    # dist_skip: "{{ vars['skip_packages_' + (ansible_distribution | lower)] | default([]) }}"


    # major_dist_pkgs: "{{ vars['packages_' + _dist_major_name] | default([]) }}"
    # major_dist_skip: "{{ vars['skip_packages_' + _dist_major_name] | default([]) }}"

    _all_pkgs: "{{ (packages_common.packages + sys_pkgs + dist_pkgs) | unique }}"
    # TODO: skip as extra var for play / CLI?
    # ll_skip: "{{ (sys_skip + dist_skip + major_dist_skip) | unique}}"
    _all_skip: "{{ [] }}"
  ansible.builtin.set_fact:
    packages: "{{ _all_pkgs | difference(_all_skip) }}"
    retired_packages: "{{ packages_common.retired + sys_retired + dist_retired | unique }}"
  tags: pkg

- name: Remove old packages
  ansible.builtin.package:
    name: "{{ retired_packages }}"
    state: absent
  become: "{{ _is_not_mac }}"
  tags: pkg

- name: Install packages
  ansible.builtin.package:
    name: "{{ packages }}"
  async: 300 # 5 minutes
  poll: 0
  register: pkg_install
  become: "{{ _is_not_mac }}"
  tags: pkg

# TODO: homebrew_cask is broken in community.general 9.0.1
- name: Install casks
  ansible.builtin.command:
    argv: "{{ base_cmd + args }}"
  async: 300 # 5 minutes
  poll: 0
  register: cask_install
  tags: [pkg, cask]
  when: _is_mac and (args | length is gt(0))
  vars:
    base_cmd: [brew, install, --cask]
    args: "{{ packages_sys.casks | default([]) }}"

- name: Install system python packages (mac only for now)
  ansible.builtin.pip:
    name: "{{ python_packages | default([]) }}"
  when: _is_mac
  become: "{{ ansible_os_family != 'Darwin' }}"
  tags: pkg