- name: Ensure ~/.local exists
  ansible.builtin.file:
    path: ~/.local
    state: directory
    mode: u=rwx,g=,o=

- name: Copy into ~/.local/bin
  ansible.builtin.copy:
    src: ../../tools/scripts/
    dest: ~/.local/bin
    directory_mode: "{{ default_dir_perms }}"
    mode: preserve
    backup: true
