---
- name: Download rhel image to libvirt images dir
  when: rhel_image_url | default(false, true)
  ansible.builtin.get_url:
    url: "{{ rhel_image_url }}"
    dest: "{{ rhel_image_dl_path }}"
    owner: qemu
    group: qemu
  become: "{{ rhel_download_become }}"

# TODO: chedk that path is properly defined
# TODO: libvirt errors for some reason?
# maybe we need to define a domain around it?
# weird cuz it says it needs to be shut down
# it worked this time???
# 

- name: Set as readonly
  ansible.builtin.file:
    path: "{{ rhel_image_dl_path }}"
    mode: u=r,g=r,o=

# https://access.redhat.com/solutions/641193 says to uninstall cloud-init, but idk why
# but that's rhel 8 and below anyway, won't do that for now.
- name: Set root password
  ansible.builtin.command:
    argv:
      - virt-customize
      - -a
      - "{{ rhel_image_dl_path }}"
      - --root-password
      - "password:{{ rhel_root_password }}"
      # - --uninstall
      # - cloud-init

# touch /.autorelabel afterward
# later: snapshot this after a single boot

# or is this all bleh and we can just enable root login over ssh?