- name: Set up CodeReady Containers / OpenShift Local
  hosts: crc_runners
  vars:
    crc_memory_mib: "{{ 24 * 1024 }}" # 16gb -> mib
    crc_disk_gib: 64 # gb
    crc_cpus: "{{ ansible_facts.processor_vcpus }}"
    crc_consent_telemetry: "yes"
    crc_enable_cluster_monitoring: "true"
    crc_pull_secret_path: "{{ ansible_facts.user_dir }}/.crc/pull_secret"
  vars_prompt:
    - name: crc_pull_secret
      prompt: "Pull secret? (press enter / use blank to skip pull secret setup)"
  tasks:
    - name: Do install
      ansible.builtin.include_role:
        name: kmg.crc.crc

    - name: Set CRC config items
      ansible.builtin.include_role:
        name: kmg.crc.crc
        tasks_from: configure.yml

    - name: Set up pull secret file contents
      ansible.builtin.copy:
        dest: "{{ crc_pull_secret_path }}"
        mode: u=r
        content: "{{ crc_pull_secret }}"
      when: (crc_pull_secret | default("") | length != 0

    - name: Set pull secret path in config
      ansible.builtin.command:
        argv:
          [crc, config, set, "pull-secret-file", "{{ crc_pull_secret_path }}"]
      changed_when: true
      when: (crc_pull_secret | default("") | length != 0
