# TODO: organize all these, probably
# off of _distribution instead of os_family.
# could have separate linux one for common.
# also what's with packages_server?
packages: # same names on any target
  - htop
  - fish
  - exa
  - bat
  - git
  - podman
  - tmux
  - ansible
  - lnav
packages_linux: # same names on any linux target
  - ripgrep
  - fd-find
  - neovim
  - python3.11
  - python3-hvac
  - dnf-plugin-system-upgrade
packages_darwin: [] # sorta redundant, we just have to pick one really
packages_macosx:
  - rg
  - fd
  - nvim
  - tokei
  - python@3.9
  - python@3.10
  - python@3.11
  - python@3.12
  - jq
  - yq
  - tree
  - moreutils
  - watch
  - node
  - golang
  - ascii
  - tokei
  - tailscale
  - vault
  - git-delta
  - openshift-cli
  - kubectl
  - helm
  - skopeo
  - just
  - gh
  - httpie
packages_darwin_casks:
  - mockoon
  - powershell
  - visual-studio-code
packages_fedora:
  - gh
  - just
  - httpie
packages_redhat: [] # rhel-specific names
retired_packages_darwin:
  - dnsmasq
  - python@3.8
retired_packages: []
retired_packages_redhat: []