- name: set up CodeReady Containers / OpenShift Local
  hosts: crc_runners
  roles: [kevinmgranger.crc.crc]

# - name: Set up networking infrastructure to reach crc remotely
#   hosts: todo
#   tasks: []
