- name: set up most things
  hosts: daily_drivers
  vars:
    default_dir_perms: u=rwx,g=,o=
    default_file_perms: u=rw,g=,o=
    default_script_perms: u=rwx,g=,o=
    packages:
      - htop
      - fish
      - exa
      - bat
      - git
      - gh
      - httpie
      - podman
      - tmux
    packages_darwin:
      - rg
      - fd
      - nvim
      - mockoon
      - tokei
      - python@3.8
      - python@3.9
      - python@3.10
      - jq
      - tree
    packages_redhat:
      - just
      - ripgrep
      - fd-find
      - neovim
      - code # todo automate this for mac as well
  tasks:
    - name: is this a graphical linux box?
      command: which dconf
      register: dconf
      ignore_errors: true

    - name: set capslock to ctrl
      community.general.dconf:
        key: /org/gnome/desktop/input-sources/xkb-options
        value: "['ctrl:nocaps']"
      when: dconf is success

    - name: set up vs code repo
      import_tasks: ../tasks/vscode-redhat.yml
      when: ansible_os_family == "RedHat"

    - name: install packages
      package:
        name: "{{ packages  + vars['packages_' + (ansible_os_family | lower)]}}"
      async: 300 # 5 minutes
      poll: 0
      register: pkg_install
      become: "{{ ansible_os_family != 'Darwin' }}"
      tags: [pkg]
    
    - name: link python
      community.general.homebrew:
        name: python@3.10
        state: linked
      when: ansible_os_family == 'Darwin'
      tags: [pkg]
    
    - name: install rust(up)
      shell:
        cmd: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        creates: ~/.cargo/bin/rustup
      async: 120
      poll: 0
      register: rustup
      tags: [rust]

    - import_tasks: "../tasks/dotfiles.yml"
      tags: [dotfiles]
    - import_tasks: "../tasks/scripts.yml"
      tags: [scripts]

    - name: wait for rust
      async_status:
        jid: "{{ rustup.ansible_job_id }}"
      register: rustup_result
      until: rustup_result.finished
      retries: 30
      delay: 5
      tags: [rust]
    
    - name: install current-kube-context
      command:
        cmd: cargo install --git https://github.com/KevinMGranger/rukube/ current-kube-context
        creates: ~/.cargo/bin/current-kube-context
      async: 150
      poll: 0
      register: kube_ctx
      tags: [kube-ctx]
      when: "'kubernauts' in group_names"

    - name: wait for packages to be installed
      async_status:
        jid: "{{ pkg_install.ansible_job_id }}"
      register: pkg_install_result
      until: pkg_install_result.finished
      retries: 30
      delay: 5
      become: "{{ ansible_os_family != 'Darwin' }}"
      tags: [fishy, pkg]

    - import_tasks: "../tasks/fish-as-default.yml"
      tags: [fishy]
    
    - name: wait for kube-ctx
      async_status:
        jid: "{{ kube_ctx.ansible_job_id }}"
      register: kube_ctx_result
      until: kube_ctx_result.finished
      retries: 30
      delay: 5
      tags: [kube-ctx]
      when: "'kubernauts' in group_names"
