- name: Set up most things
  hosts: daily_drivers
  vars:
    default_dir_perms: u=rwx,g=,o=
    default_file_perms: u=rw,g=,o=
    default_script_perms: u=rwx,g=,o=

    _do_kube_setup: "{{ do_kube_setup | default('kubernauts' in group_names) }}"
    _install_rust: "{{ install_rust | default('rusty' in group_names) }}"

    python_packages:
      - ansible-lint
    #   - requests
    #   - attrs
    #   - cryptography
    #   - hvac
    #   - click
    packages:
      - htop
      - fish
      - exa
      - bat
      - git
      - gh
      - httpie
      - podman
      - tmux
      - just
      - ansible
    packages_darwin:
      - rg
      - fd
      - nvim
      - tokei
      - python@3.9
      - python@3.10
      - python@3.11
      - jq
      - yq
      - tree
      - moreutils
      - watch
      - node
      - golang
      - ascii
      - tokei
      - tailscale
      - vault
      - git-delta
      - openshift-cli
      - kubectl
      - helm
      - skopeo
    packages_darwin_casks:
      - mockoon
      - powershell
      - visual-studio-code
    packages_redhat:
      - ripgrep
      - fd-find
      - neovim
      - python3.11
      - python3-hvac
    retired_packages_darwin:
      - dnsmasq
      - python@3.8
    retired_packages: []
    retired_packages_redhat: []
  tasks:
    - name: Remove old packages
      ansible.builtin.package:
        name: "{{ retired_packages + vars['retired_packages_' + (ansible_os_family | lower)] }}"
        state: absent
      become: "{{ ansible_os_family != 'Darwin' }}"
      tags: [pkg]

    - name: Install packages
      ansible.builtin.package:
        name: "{{ packages + vars['packages_' + (ansible_os_family | lower)] }}"
      async: 300 # 5 minutes
      poll: 0
      register: pkg_install
      become: "{{ ansible_os_family != 'Darwin' }}"
      tags: [pkg]

    - name: Install casks
      community.general.homebrew_cask:
        name: "{{ packages_darwin_casks }}"
      async: 300 # 5 minutes
      poll: 0
      register: cask_install
      become: false
      when: "ansible_os_family == 'Darwin'"
      tags: [pkg]

    - name: Install system python packages (mac only for now)
      ansible.builtin.pip:
        name: "{{ python_packages }}"
      when: "ansible_os_family == 'Darwin'"
      become: "{{ ansible_os_family != 'Darwin' }}"
      tags: [pkg]

    - name: Install rust(up) # noqa command-instead-of-module
      ansible.builtin.shell:
        cmd: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        creates: ~/.cargo/bin/rustup
      async: 120
      poll: 0
      register: rustup
      tags: [rust]
      when: _install_rust

    - name: Handle dotfiles
      ansible.builtin.import_tasks: "../tasks/dotfiles.yml"
      tags: [dotfiles]

    - name: Copy kube ctx fish prompt part
      ansible.builtin.copy:
        mode: "{{ default_file_perms }}"
        src: ../../config-files/fish_extra/05-kubernetes-prompt.fish
        dest: ~/.config/fish/conf.d/_manual_source/prompt_parts.d/
      when: _do_kube_setup
      tags: [kube-ctx]

    - name: Handle scripts
      ansible.builtin.import_tasks: "../tasks/scripts.yml"
      tags: [scripts]

    - name: Wait for rust
      ansible.builtin.async_status:
        jid: "{{ rustup.ansible_job_id }}"
      register: rustup_result
      until: rustup_result.finished
      retries: 30
      delay: 5
      tags: [rust]
      when: rustup_result is defined

    - name: Install current-kube-context
      ansible.builtin.command:
        cmd: cargo install --git https://github.com/KevinMGranger/rukube/ current-kube-context
        creates: ~/.cargo/bin/current-kube-context
      async: 150
      poll: 0
      register: kube_ctx
      tags: [kube-ctx]
      when: _do_kube_setup

    - name: Wait for packages to be installed
      ansible.builtin.async_status:
        jid: "{{ pkg_install.ansible_job_id }}"
      register: pkg_install_result
      until: pkg_install_result.finished
      retries: 30
      delay: 5
      become: "{{ ansible_os_family != 'Darwin' }}"
      tags: [fishy, pkg]

    - name: Wait for casks to be installed
      ansible.builtin.async_status:
        jid: "{{ cask_install.ansible_job_id }}"
      register: cask_install_result
      until: cask_install_result.finished
      retries: 30
      delay: 5
      become: false
      tags: [fishy, pkg]
      when: "ansible_os_family == 'Darwin'"

    - name: Set fish to default shell
      ansible.builtin.import_tasks: "../tasks/fish-as-default.yml"
      tags: [fishy]

    - name: Wait for kube-ctx
      ansible.builtin.async_status:
        jid: "{{ kube_ctx.ansible_job_id }}"
      register: kube_ctx_result
      until: kube_ctx_result.finished
      retries: 30
      delay: 5
      tags: [kube-ctx]
      when: kube_ctk_result is defined
