- name: Set hosts and hostnames
  hosts: all
  tasks:
    - name: Set hostname
      become: true
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
        use: systemd

    - name: Put all non-local hosts in /etc/hosts
      become: true
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ item.value }} {{ item.key }}"
      loop: "{{ dict(hostvars.keys() | zip(hostvars.values() | map(attribute='ansible_host'))) | dict2items }}"
      when: inventory_hostname != item.key

    - name: Put localhost in /etc/hosts
      become: true
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: 127.0.0.1 {{ inventory_hostname }}
