- name: copy into ~/.config
  copy:
    src: ../../config-files/config/
    dest: ~/.config
    directory_mode: "{{ default_dir_perms }}"
    mode: preserve
    backup: yes

- name: copy mac fish config
  when: ansible_system == "Darwin"
  copy:
    src: ../../config-files/mac-wrappers.fish
    dest: ~/.config/fish/conf.d/
    mode: preserve
