- name: copy into ~/.config
  copy:
    src: ../../config-files/config/
    dest: ~/.config
    directory_mode: "{{ default_dir_perms }}"
    mode: preserve
    backup: yes

- name: copy emoji config
  template:
    src: ../../config-files/01_emoji_prompt.fish.j2
    dest: ~/.config/fish/conf.d/01_emoji_prompt.fish

- name: copy mac fish config
  when: ansible_system == "Darwin"
  copy:
    src: ../../config-files/mac.fish
    dest: ~/.config/fish/conf.d/
    mode: preserve
