- name: Copy into ~/.config
  ansible.builtin.copy:
    src: ../../config-files/config/
    dest: ~/.config
    directory_mode: "{{ default_dir_perms }}"
    mode: preserve
    backup: true

- name: Copy emoji config
  ansible.builtin.template:
    src: ../../config-files/fish_extra/01_emoji_prompt.fish.j2
    dest: ~/.config/fish/conf.d/01_emoji_prompt.fish
    mode: preserve

- name: Copy mac fish config
  when: ansible_system == "Darwin"
  ansible.builtin.copy:
    src: ../../config-files/fish_extra/mac.fish
    dest: ~/.config/fish/conf.d/
    mode: preserve
