- name: Get fish path
  ansible.builtin.command: which fish
  changed_when: false
  register: fish_path_output
  tags: [become]

- name: Ensure fish presence in /etc/shells
  become: true
  ansible.builtin.lineinfile:
    line: "{{ fish_path_output.stdout }}"
    path: /etc/shells
  tags: [become]

- name: Make sure sbin is in path on RHEL
  become: true
  ansible.builtin.lineinfile:
    line: fish_add_path /usr/sbin
    path: /etc/fish/config.fish
  tags: [become]
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "9"

- name: Set shell
  become: true
  ansible.builtin.user:
    name: kevin
    shell: "{{ fish_path_output.stdout }}"
  tags: [become]
