- name: ensure ~/.local exists
  file:
    path: ~/.local
    state: directory
    mode: u=rwx,g=,o=

- name: copy into ~/.local/bin
  copy:
    src: ../../tools/scripts/
    dest: ~/.local/bin
    directory_mode: "{{ default_dir_perms }}"
    mode: preserve
    backup: yes