- name: ensure ~/.local exists
  file:
    path: ~/.local
    state: directory
    mode: preserve

- name: copy into ~/.local/bin
  # TODO DOES THIS JUST NEST IT
  copy:
    src: ../../tools/scripts
    dest: ~/.local/bin
    recurse: yes
    directory_mode: preserve
    mode: preserve
    backup: yes