- rpm_key:
    key: https://packages.microsoft.com/keys/microsoft.asc
  become: yes

- copy:
    content: |
      [code]
      name=Visual Studio Code
      baseurl=https://packages.microsoft.com/yumrepos/vscode
      enabled=1
      gpgcheck=1
      gpgkey=https://packages.microsoft.com/keys/microsoft.asc"
    dest: /etc/yum.repos.d/vscode.repo
  become: yes
