packages: # common to all distros
- ripgrep
- fd-find
- neovim
- python3.11
- python3.12
# - python3-hvac # on pause
- dnf-plugin-system-upgrade
fedora:
- gh
- just
- httpie
- policycoreutils-python-utils
redhat: [] # rhel-specific names

# TODO: how to handle this properly (or ignore?)
skip_packages_redhat_8:
  - exa
  - bat