- name: Include package vars
  ansible.builtin.import_tasks: packages/include_package_vars.yaml

- name: Throw if not mac
  ansible.builtin.assert:
    that: _is_mac
    fail_msg: >-
      Package config drift check is
      only available on mac for now

- name: Get homebrew package info
  when: _is_mac
  kmg.infra.brew_package_info:
  register: _brew_packages

- name: Check for drift
  ansible.builtin.assert:
    that: present_but_unspecified | length == 0
    fail_msg: >-
      The following packages are present on the system
      but not specified in the config:

      {{ present_but_unspecified | join("\n") }}
  vars:
    leaves: >-
      {{
        _brew_packages.packages.values()
        | selectattr('leaf')
        | map(attribute='name')
      }}
    # TODO: full name handling, cask handling
    present_but_unspecified: "{{ leaves | difference(packages) }}"
