vs_code_settings: >
  {{ lookup('ansible.builtin.file', 'settings.yaml')
    | from_yaml }}

extensions:
  - 1dot75cm.RPMSpec
  - bungcip.better-toml
  - eamodio.gitlens
  - fcrespo82.markdown-table-formatter
  - golang.go
  - kangping.protobuf
  - ms-kubernetes-tools.vscode-kubernetes-tools
  - ms-python.python
  - ms-python.vscode-pylance
  - ms-toolsai.jupyter
  - ms-toolsai.jupyter-keymap
  - ms-toolsai.jupyter-renderers
  - ms-toolsai.vscode-jupyter-cell-tags
  - ms-toolsai.vscode-jupyter-slideshow
  - ms-vscode-remote.remote-ssh
  - ms-vscode-remote.remote-ssh-edit
  - ms-vscode.makefile-tools
  - ms-vsliveshare.vsliveshare
  - redhat.ansible
  - redhat.vscode-yaml
  - rust-lang.rust-analyzer
  - skyapps.fish-vscode
  - vadimcn.vscode-lldb
  - vscodevim.vim
  - wholroyd.jinja