---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: devspaces-sub
  namespace: openshift-operators 
spec:
  channel: stable
  name: devspaces
  source: redhat-operators 
  sourceNamespace: openshift-marketplace 
---
apiVersion: project.openshift.io/v1
kind: ProjectRequest
metadata:
  name: devspaces