---
apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: devspaces
  namespace: devspaces
spec:
  components:
    cheServer:
      debug: false
      logLevel: INFO
    metrics:
      enable: true
# TODO: these are defaults from the web interface.
# is any of this required?
  # containerRegistry: {}
  # devEnvironments:
  #   startTimeoutSeconds: 300
  #   secondsOfRunBeforeIdling: -1
  #   maxNumberOfWorkspacesPerUser: -1
  #   containerBuildConfiguration:
  #     openShiftSecurityContextConstraint: container-build
  #   defaultNamespace:
  #     autoProvision: true
  #     template: <username>-devspaces
  #   secondsOfInactivityBeforeIdling: 1800
  #   storage:
  #     pvcStrategy: per-user
  # gitServices: {}
  # networking: {}
