---
- name: Download Image
  ansible.builtin.include_tasks: "download_rhel_image.yml"

- name: Define VM
  become: true
  ansible.builtin.command:
    argv:
      - virt-install
      - --name
      - "{{ item.name }}"
      - --memory
      - "{{ item.memory }}"
      - --vcpus
      - "{{ item.cpus }}"
      - "--import"
      - --disk
      - pool=images,size={{ item.storage }},backing_store={{ rhel_image_dl_path }}
      - --osinfo
      - detect=on,require=on
  loop:
    - {name: aap-tower-host, memory: 16GiB, cpus: }